# Generated by Django 3.0.2 on 2020-01-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('month_limit', models.FloatField(max_length=1000000)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
    ]
