# Generated by Django 3.0.2 on 2020-01-30 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200128_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=58),
        ),
        migrations.AlterField(
            model_name='category',
            name='month_limit',
            field=models.FloatField(max_length=1000000, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
