# Generated by Django 3.0.2 on 2020-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
